module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'test',
        'chore',
        'refactor',
        'perf',
        'security',
        'ci',
        'revert',
        'build',
        'style',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'auth',
        'gateway',
        'orders',
        'drivers',
        'fleet',
        'storefronts',
        'payments',
        'dispatch',
        'tracking',
        'comms',
        'blockchain',
        'iot',
        'ai',
        'agents',
        'analytics',
        'logistics',
        'esg',
        'loyalty',
        'insurance',
        'admin',
        'corporate',
        'investor',
        'developer-portal',
        'command-centre',
        'shared-types',
        'shared-ui',
        'shared-utils',
        'infra',
        'terraform',
        'helm',
        'docker',
        'ci',
        'deps',
        'monorepo',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'header-max-length': [2, 'always', 100],
    'body-max-line-length': [1, 'always', 200],
  },
};
